dist: bionic
language: cpp
compiler: gcc

addons:
  apt:
    update: true
    packages:
        - cmake
        - cut
        - libsdl2-dev
        - libsdl2-gfx-dev
git:
  depth: 3

before_install:
  - wd="$PWD" && cd .. && git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install && cd $wd && cat /etc/os-release | head -n 1

script:
  - cmake -H. -Bbuild
  - cmake --build build --target eve
  - cmake --build build --target tests && ./build/tests
