dist: bionic
language: cpp
compiler: gcc

git:
        depth: 3

before_install:
        - git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install
