dist: bionic
language: cpp
compiler: gcc

addons:
  apt:
    update: true
    packages:
        - cmake
        - libsdl2-2.0-0
        - libsdl2-gfx-1.0-0
git:
  depth: 3

before_install:
  - wd="$PWD" && cd .. && git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install && cd $wd
  - apt list --installed

script:
  - cmake -H. -Bbuild
  - cmake --build build --target eve
  - cmake --build build --target tests && ./build/tests
